name: Release (Master)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ././WJS.ExtraLifeStreamLabelsCore/WJS.ExtraLifeStreamLabelsCore.sln
    - name: Build
      run: dotnet build ././WJS.ExtraLifeStreamLabelsCore/WJS.ExtraLifeStreamLabelsCore.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ././WJS.ExtraLifeStreamLabelsCore/WJS.ExtraLifeStreamLabelsCore.sln --no-restore --verbosity normal
